import Navbar from "./navbar";
import Head from "next/head";

export const Top = () => {
  return (
    <>
      <Head>
        <title>E&N Contracting Group</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ENicon.svg" />
        <html lang="en" />
      </Head>

      <Navbar />
    </>
  );
};
