import Link from "next/link";
import Image from "next/image";
import Navbar from "../../components/navbar";
import Head from "next/head";
import { AllProducts } from "../../components/allproducts";

export default function About() {
  //list of services
  const serviceOfferings = [{ one: "two" }, { one: "two" }, { one: "two" }];

  return (
    <div>
      <Head>
        <title>E&N Contracting Group</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ENicon.svg" />
      </Head>

      <Navbar />

      <main>
        <AllProducts />
      </main>
    </div>
  );
}
