import Head from "next/head";
import Image from "next/image";
import { AboutUs } from "../components/aboutus";
import Navbar from "../components/navbar";
import { Statistics } from "../components/stats";

export default function About() {
  return (
    <div>
      <Head>
        <title>E&N Contracting Group</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ENicon.svg" />
      </Head>

      <Navbar />

      <main>
        <AboutUs />
        <Statistics />
      </main>
    </div>
  );
}
