import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Hero } from "../components/hero";
import Navbar from "../components/navbar";
import { Reviews } from "../components/reviews";
import { TopServices } from "../components/topservices";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>E&N Contracting Group</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ENicon.svg" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <Hero />
        <TopServices />
        <Reviews />
      </main>

      <footer className={styles.footer}>
        <p>Copyright © {new Date().getFullYear()} E&N Contracting Group</p>

        <a
          href="https://purplelanterndesign.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Build by{"  "}
          <span className={styles.logo}>
            <Image
              src="/PL_Logo.svg"
              alt="Purple Lantern Logo"
              width={152}
              height={76}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
