import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Hero } from "../components/hero";
import Navbar from "../components/navbar";
import { Reviews } from "../components/reviews";
import { TopServices } from "../components/topservices";
import { client, urlFor } from "../sanity";

export default function Home({ data, reviews, products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>E&N Contracting Group</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ENicon.svg" />
        <html lang="en" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <Hero hero={data} />
        <TopServices products={products} />
        <Reviews reviews={reviews} />
      </main>

      <footer className={styles.footer}>
        <p>Copyright © {new Date().getFullYear()} E&N Contracting Group</p>

        <a
          href="https://purplelanterndesign.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Build by{"  "}
          <span className={styles.logo}>
            <Image
              src="/PL_Logo.svg"
              alt="Purple Lantern Logo"
              width={152}
              height={76}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}

export const getStaticProps = async () => {
  const mainquery = `*[_type == "home"][1] {
    _id,
    title,
    mainImage,
    overview,
}`;

  const reviewquery = `*[_type == "review"] {
    _id,
    name,
    company,
    mainImage,
    body
    }`;

  const productquery = ` *[_type == "product"] {
    _id,
    title,
    mainImage,
    slug {
      current
    }
    }`;

  const data = await client.fetch(mainquery);
  const reviews = await client.fetch(reviewquery);
  const products = await client.fetch(productquery);

  return {
    props: {
      data,
      reviews,
      products,
    },

    revalidate: 10,
  };
};
